version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: claims_db
    restart: always
    environment:
      - POSTGRES_USER=actuary
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=claims_warehouse
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432" # We stick to 5433 to avoid conflict with your Scraper DB
